"""Constants for the game."""

import notty
from notty.src.utils import get_window_size

APP_NAME = notty.__name__

ANIMATION_SPEED = 15

MAX_HAND_SIZE = 20
MAX_PLAYERS = 3
MIN_PLAYERS = 2
INITIAL_HAND_SIZE = 4

TOTAL_CARDS = 90

NUM_HAND_COLUMNS = 5
NUM_HAND_ROWS = 4

ANTI_ALIASING = True

APP_WIDTH, APP_HEIGHT = get_window_size()
APP_WIDTH -= 200
APP_HEIGHT -= 100

PLAYER_WIDTH = APP_WIDTH // 10
PLAYER_HEIGHT = APP_HEIGHT // 5

CARD_WIDTH, CARD_HEIGHT = PLAYER_WIDTH // 3, PLAYER_HEIGHT // 3

DECK_WIDTH, DECK_HEIGHT = CARD_WIDTH * 3, CARD_HEIGHT * 3

# deck should be at top center
DECK_POS_X = (APP_WIDTH - DECK_WIDTH) // 2
DECK_POS_Y = 0

HAND_HEIGHT = CARD_HEIGHT * NUM_HAND_ROWS
HAND_WIDTH = CARD_WIDTH * NUM_HAND_COLUMNS

# action board
ACTION_BOARD_WIDTH = HAND_WIDTH
ACTION_BOARD_HEIGHT = PLAYER_HEIGHT + HAND_HEIGHT
# action board should be top right
ACTION_BOARD_X = APP_WIDTH - ACTION_BOARD_WIDTH
ACTION_BOARD_Y = 0
